site_name: Lighthouse cATO Playbook
site_url: https://department-of-veterans-affairs.github.io/lighthouse-cato-playbook
repo_url: https://github.com/department-of-veterans-affairs/lighthouse-cato-playbook
edit_uri: edit/main/docs/
repo_name: lighthouse-cato-playbook
theme:
  name: material
  logo: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/department-of-veterans-affairs/lighthouse-cato-playbook
    - icon: fontawesome/brands/slack
      link: https://lighthouseva.slack.com/archives/C03G2J6G7AR
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
plugins:
  - search
  - print-site
nav:
  - 'Prologue': 'index.md'
  - 'Introduction': 
      - 'Overview': 'overview.md'
      - 'Approach': 'approach.md'
      - 'Benefits': 'benefits.md'
  - 'Process':
      - 'Overview': 'process.md'
      - 'checklist.md'
      - 'categorization.md'
      - 'privacy.md'
      - 'diagram.md'
      - 'selection.md'
      - 'pipeline.md'
      - 'platform.md'
      - 'testing.md'
 - 'Policies': 
      - 'policy.md'
      - 'poam.md'
  - 'monitoring.md'
  - 'Support':
    - 'contact.md'
    - 'FAQ': 'faq.md'
