site_name: Lighthouse cATO Playbook
site_url: https://department-of-veterans-affairs.github.io/lighthouse-cato-playbook
repo_url: https://github.com/department-of-veterans-affairs/lighthouse-cato-playbook
edit_uri: edit/main/docs/
theme:
  name: material
markdown_extensions:
  - abbr
  - footnotes
nav:
  - 'index.md'
  - 'Approach':
      - 'Overview': 'approach.md'
      - 'Benefits': 'benefits.md'
  - 'stack.md'
  - 'pipeline.md'
  - 'policy.md'
  - 'contact.md'