site_name: cATO Playbook
site_url: https://rise8-us.github.io/cato-playbook
repo_url: https://github.com/rise8-us/cato-playbook
edit_uri: edit/main/docs/
repo_name: cato-playbook
theme:
  name: material
#  logo: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.expand
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rise8-us/cato-playbook
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
plugins:
  - search
  - print-site
nav:
  - README: 'index.md'
  - 'Introduction': 
      - 'The Why': 'why.md'
      - 'History': 'history.md'
      - 'Laws and Regulations': 'laws.md'
      - 'Myths': 'myths.md'
      - 'misconceptions.md'
  - 'Recommended Approach':
      - 'Overview': 'overview.md'
      - 'people.md'
      - 'policy.md'
      - 'Integrated Process & Technology':
          - 'prepare.md'
          - 'categorize.md'
          - 'select.md'
          - 'implement-assess.md'
          - 'initial-auth.md'
          - 'monitor.md'
          - 'ongoing-auth.md'
          - 'outcomes.md'
          - 'community.md'
  - 'Plays':
      - 'organize.md'
      - 'assessors.md'
      - 'communications.md'
      - 'ucd.md'
      - 'education.md'
      - 'mythbusting.md'
      - 'sdlc.md'
      - 'inheritance.md'
      - 'modularity.md'
      - 'grc-agreement.md'
      - 'oscal.md'
      - 'pipeline.md'
      - 'implementation-workflow.md'
      - 'integrate.md'
      - 'document.md'
      - 'sla.md'
      - 'commit.md'
      - 'runtime.md'
      - 'dora.md'
      - 'checks.md'
      - 'advanced.md'
      - 'zero-based.md'
      - 'renewal.md'
