site_name: Lighthouse cATO Playbook
site_url: https://department-of-veterans-affairs.github.io/lighthouse-cato-playbook
repo_url: https://github.com/department-of-veterans-affairs/lighthouse-cato-playbook
edit_uri: edit/main/docs/
theme:
  name: material
markdown_extensions:
  - abbr
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'index.md'
  - 'Approach':
      - 'Overview': 'approach.md'
      - 'Benefits': 'benefits.md'
  - 'architecture.md'
  - 'Process':
      - 'Overview' : 'process.md'
      - 'diagram.md'
      - 'selection.md'
      - 'pipeline.md'
      - 'platform.md'
      - 'checklist.md'
  - 'policy.md'
  - 'contact.md'